services:
  - type: web
    name: spirit-api
    env: node
    region: oregon  # or your preferred region
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
